server:
  port: 80

spring:
    datasource:
        name: supervisions
        url: jdbc:mysql://localhost:3306/supervisions
        username: root
        password: 123456
        # \u4F7F\u7528druid\u6570\u636E\u6E90
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
        # Redis服务器地址
        host: localhost
        # Redis服务器连接密码（默认为空）
        password: 123456
        # Redis服务器连接端口
        port: 6379
        # Redis数据库索引（默认为0 redis有16个库）
        database: 0
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接超时时间（毫秒）
          timeout: 0

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.supervisions.modules.mapper
  config-location: classpath:config/mybatis-config.xml

#pagehelper\u5206\u9875\u63D2\u4EF6
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql